### ISSUE TITLE
Improved macros for filament loading / change

### ISSUE THREAD

**Issue by xblax** [xblax/flashforge_adm5_klipper_mod#16]
The current Macro for filament loading is quite basic (`LOAD_FILAMENT`). This should be replaced with a nicer mechanism using Macro Prompts: https://docs.mainsail.xyz/overview/features/macro-prompts

Idea is that load LOAD_FILAMENT macro can be used and then the user is asked about Filament Type, Extrude Length. Should also have a wait that requires confirmation to proceed after nozzle heat-up was completed.

**Comment by consp** [comment]
Mentioning #52 since it's related.

**Comment by xblax** [comment]
The macro `LOAD_MATERIAL` is now in for interactive load and unload of filament.
