### ISSUE TITLE
NFS client support

### ISSUE THREAD

**Issue by KaruroChori** [xblax/flashforge_adm5_klipper_mod#45]
> I thought nfs was build into the kernel already but i could be mistaken? Maybe just the user space parts missing. Good point though. Maybe make a separate issue for it @KaruroChori ?

_Originally posted by @consp in https://github.com/xblax/flashforge_adm5_klipper_mod/issues/17#issuecomment-1987137854_
            
On debian-based systems I always have to install additional packets including executables like mount.nfs, so I think there is some userspace stuff missing.
I cannot check it right now, so I will update this at a later date.

**Comment by KaruroChori** [comment]
I will find a workaround for the fstab entries. Otherwise I am sure I will forget about it next time I upgrade the firmware, so I better fix it for good :D.

The next stage is to use cheap thin clients as klipper hosts, with v-pro enabled for remote management, and to boot via PXE :D.
In all seriousness, I always wondered how big print farms handles their infrastructure.

**Comment by xblax** [comment]
Noticed that the NFS Server Daemon can be disabled separately, therefore removed it from the build:
https://github.com/xblax/flashforge_adm5_klipper_mod/commit/73cd74bb46ef9b8bdc9070b4fdcbdc349979c4c6

**Comment by consp** [comment]
> Noticed that the NFS Server Daemon can be disabled separately, therefore removed it from the build: [73cd74b](https://github.com/xblax/flashforge_adm5_klipper_mod/commit/73cd74bb46ef9b8bdc9070b4fdcbdc349979c4c6)

Completely missed that, must have read it as RPC client. That is a way better option.

**Comment by xblax** [comment]
I'm going to close this since NFS client support was added and no open points at the moment. If there should be any issues this can be re-opened or tracked separately.
