### ISSUE TITLE
Filament runout sensor not working

### ISSUE THREAD

**Issue by johncotten** [xblax/flashforge_adm5_klipper_mod#50]
The filament runout sensor does not appear to be on PB14. I also found reference of a PE1 but that does not appear to be correct either. 

Config in printer.base.cfg

[filament_switch_sensor runout_sensor]
pause_on_runout: False
switch_pin: !PB14
event_delay: 1.0

**Comment by KaruroChori** [comment]
There were two filament runout sensors in the very first version, both disabled by default.
In theory, the one not used was disabled.

Could it be that different board revisions have one or the other connected?

**Comment by consp** [comment]
Stock also seems to ignore the sensor. Dees anyone know it actually works?

**Comment by jtenniswood** [comment]
Yes it does work on stock, I have experienced the printer parking when the sensor was triggered.

**Comment by consp** [comment]
I guess there is some additional magic somewhere, diving into stock now to see what goes on.

**Comment by consp** [comment]
Reloading the original cfg works, I can now detect it.

**Comment by consp** [comment]
The fix is pushed to master, strange but true. I guess it's a configuration thing as the PE1 pin is not exposed on the 48 or 64 pin package.

**Comment by xblax** [comment]
@consp Can you rename it to "_e1_sensor"? Then it should not show up in the Gui and confuse everyone.

**Comment by consp** [comment]
> @consp Can you rename it to "_e1_sensor"? Then it should not show up in the Gui and confuse everyone.


sure, I'll amend it and force push for niceness

**Comment by DougJoseph** [comment]
Thank you all for catching and fixing this! I just have one question. Where it says “pause at runout” is set to false, I would think that you would want it to pause at runout. Am I misunderstanding how that code is intended to function?

**Comment by xblax** [comment]
> Thank you all for catching and fixing this! I just have one question. Where it says “pause at runout” is set to false, I would think that you would want it to pause at runout. Am I misunderstanding how that code is intended to function?

Yes, good point. I will try to test it.

**Comment by xblax** [comment]
@DougJoseph 
I did now properly integrate the runout sensor with some macros:

![image](https://github.com/xblax/flashforge_adm5_klipper_mod/assets/9802544/661e199c-b445-4a66-95d9-db7d0df7d51f)

This will be in the next release.

**Comment by DougJoseph** [comment]
Wow you are amazing!! Thank you!!
