### ISSUE TITLE
Extrude X from mainsail or fluidd

### ISSUE THREAD

**Issue by byovic** [xblax/flashforge_adm5_klipper_mod#60]
When I try to extrude X no matter the value seems to extrude the same amount each time.  From both frontends when the value is changed still same amount.

**Comment by xblax** [comment]
Could it be the case that you just need to confirm the filament length wither Enter before press the 'Extrude' button? It's not very intuitive.

Otherwise extrusion G-Code should also be logged in the console to confirm it's doing the right thing.

**Comment by xblax** [comment]
I cannot reproduce the issue. Extrusion via Mainsail/Fluidd works fine. 
If there's an actual issue we need more information about what was tried and does not work.
