### ISSUE TITLE
Can't save new probe offset in klipperscreen or mainsail

### ISSUE THREAD

**Issue by THEGxHOxST** [xblax/flashforge_adm5_klipper_mod#81]
I noticed an issue saving bed offsets within the Klipper screen and mainsail interface when trying to use the SAVE_CONFIG command. 
Easy fix however, just move the probe section from Printer.base.cfg to Printer.cfg.

**Comment by consp** [comment]
> Easy fix however, just move the probe section from Printer.base.cfg to Printer.cfg

See https://github.com/xblax/flashforge_adm5_klipper_mod/discussions/61

Already fixed in https://github.com/xblax/flashforge_adm5_klipper_mod/commit/8309829b0a69ce625ac81950660cf6bd2d7669b9
