### ISSUE TITLE
Need to rename M25

### ISSUE THREAD

**Issue by johncotten** [xblax/flashforge_adm5_klipper_mod#82]
When using Orca and inserting a pause, it sends command M25. Printer does not want to resume and gives error: "Print is not paused, resume aborted".

I inserted this following code into macros and that behavior disappears.

```
[gcode_macro M25]
rename_existing: M25.1
gcode:
  PAUSE

```

**Comment by xblax** [comment]
Do we know that's the difference between the M25 and the PAUSE? 
M25 is "Pause SD print", the error "Print is not paused, resume aborted" I would maybe expect from M24 "Start/resume SD print". Anyway, probably both should be handled:

```
[gcode_macro m24]
rename_existing: M24.6245197
gcode:
  {% if printer.pause_resume.is_paused %}
  RESUME
  {% else %}
  M24.6245197
  {% endif %}

[gcode_macro m25]
rename_existing: M25.6245197
gcode:
  PAUSE
```

Found this example here https://github.com/jschuh/klipper-macros/blob/main/pause_resume_cancel.cfg

**Comment by xblax** [comment]
I added these macros, will be in the next release.
