### ISSUE TITLE
[probe] settings in included file causes error when saving z offset

### ISSUE THREAD

**Issue by monkeyWad** [xblax/flashforge_adm5_klipper_mod#89]
When saving the configuration after auto leveling, you get the error `SAVE_CONFIG section 'probe' option 'z_offset' conflicts with included value`. The cause of this is that the [probe] configuration section is in the included file printer.base.cfg. Moving the [probe] section to the main printer.cfg resolves this issue.

**Comment by xblax** [comment]
Thanks for the report, but we have already fixed it :)
See https://github.com/xblax/flashforge_adm5_klipper_mod/discussions/61 and the fix https://github.com/xblax/flashforge_adm5_klipper_mod/commit/8309829b0a69ce625ac81950660cf6bd2d7669b9

It will be in the next release, in the meantime I would recommend to update the configs from git https://github.com/xblax/flashforge_adm5_klipper_mod/tree/master/printer_configs

Some other improvements and fixes are being worked on at the moment in the issues and discussion section.
