### ISSUE TITLE
Could we add Exclude Objects as an enhancement?

### ISSUE THREAD

**Issue by johncotten** [xblax/flashforge_adm5_klipper_mod#95]
I just ran a print that it would be nice to skip the remainder of one of the objects. Looks like maybe we just need to unhide a panel in Mainsail and Fluidd. Not sure the memory impact of this.

https://docs.mainsail.xyz/overview/features/exclude-objects

**Comment by xblax** [comment]
Afaik it's already supported. Have you tried printing such a G-Code file with multiple objects? I think I have already noticed the dashed square to skip a single object.

Maybe the exclude object panel bust be enabled in the Mainsail options.

**Comment by xblax** [comment]
Can confirm that this already works:

![image](https://github.com/xblax/flashforge_adm5_klipper_mod/assets/9802544/133d4c75-7ac6-4ba8-a400-1043f242b001)
